FROM python:3.9.9-buster

ENV TEMP_FOOBAR_SRC /civis_python_src

COPY ./ $TEMP_FOOBAR_SRC/

RUN pip install --no-cache-dir -r $TEMP_FOOBAR_SRC/requirements.txt && \
    pip install --no-cache-dir $TEMP_FOOBAR_SRC/. && \
    rm -rf $TEMP_FOOBAR_SRC
